<a href="https://colab.research.google.com/github/SuminBae97/PytorchStudy/blob/main/Regression_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F




In [2]:
xtrain = torch.FloatTensor([[1],[2],[3]])
ytrain = torch.FloatTensor([[2],[4],[6]])


In [3]:
model = nn.Linear(1,1)

In [4]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3054]], requires_grad=True), Parameter containing:
 tensor([-0.3602], requires_grad=True)]

In [5]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)

In [6]:
nb_epochs=2000

for epoch in range(nb_epochs+1):
    prediction = model(xtrain)
    cost = F.mse_loss(prediction,ytrain)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 ==0:
        print('Epoch{:4d}/{} cost: {:.6f}'.format(epoch,nb_epochs,cost.item()))
    

Epoch   0/2000 cost: 28.252813
Epoch 100/2000 cost: 0.026616
Epoch 200/2000 cost: 0.016447
Epoch 300/2000 cost: 0.010163
Epoch 400/2000 cost: 0.006280
Epoch 500/2000 cost: 0.003881
Epoch 600/2000 cost: 0.002398
Epoch 700/2000 cost: 0.001482
Epoch 800/2000 cost: 0.000916
Epoch 900/2000 cost: 0.000566
Epoch1000/2000 cost: 0.000350
Epoch1100/2000 cost: 0.000216
Epoch1200/2000 cost: 0.000134
Epoch1300/2000 cost: 0.000083
Epoch1400/2000 cost: 0.000051
Epoch1500/2000 cost: 0.000032
Epoch1600/2000 cost: 0.000019
Epoch1700/2000 cost: 0.000012
Epoch1800/2000 cost: 0.000007
Epoch1900/2000 cost: 0.000005
Epoch2000/2000 cost: 0.000003


In [7]:
test = torch.FloatTensor([[4]])


In [8]:
prediction = model(test)


In [9]:
prediction

tensor([[7.9966]], grad_fn=<AddmmBackward0>)

Building Regression model with Class

In [34]:
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)

    def forward(self,x):
        return self.linear(x)

model = LinearRegression()        



In [36]:
model = LinearRegressionModel()        
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)



NameError: ignored

In [12]:
# nb_epochs=2000

# for epoch in range(nb_epochs+1):
#     prediction = model(xtrain)
    
#     #cost 계산
#     cost = F.mse_loss(prediction,ytrain)

#     #기울기 0으로 초기화
    
#     optimizer.zero_grad()
#     cost.backward()

#     #weight bias update
#     optimizer.step()

#     if epoch%100==0:
#         print('Epoch : {:4d}/ {} Cost : {:.6f}'.format(epoch, nb_epochs,cost.item()))




In [13]:
pred = model(torch.FloatTensor([[10]]))

In [14]:
pred

tensor([[-6.5891]], grad_fn=<AddmmBackward0>)

Multi variate Linear Regression

In [37]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [45]:
model = MultivariateLinearRegressionModel()
optimizer = torch.optim.SGD(model.parameters(),lr=1e-5)


In [46]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4632,  0.4528,  0.3256]], requires_grad=True),
 Parameter containing:
 tensor([0.2933], requires_grad=True)]

In [47]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
# nb_epochs =10000
# for epoch in range(nb_epochs+1):
    
#     prediction = model(x_train)
#     cost = F.mse_loss(prediction,y_train)

#     optimizer.zero_grad()
#     cost.backward()
#     optimizer.step()

#     if epoch%100==0:

#     # 100번마다 로그 출력
#         print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

In [50]:
test = torch.FloatTensor(
    [[73,80,75]]
)

In [51]:
model(test)

tensor([[151.1958]], grad_fn=<AddmmBackward0>)